/*
 * YunX (云析) - A network drive share-link parser and high-speed downloader for Android.
 * Copyright (C) 2026 CYQawa
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// ★ 必须 import 后用短名，不能写 `java.time.ZonedDateTime` 这种全限定名：
//   Kotlin DSL 脚本作用域里 `java` 会被解析为 Java 插件扩展访问器（而非根包），
//   导致 `java.time` 报 Unresolved reference 'time'（Gradle 9 + Kotlin 2.2 必现）。
//   import 按类路径全限定名解析、不受脚本作用域影响，因此改用短名引用。
//   本脚本内**任何** java.* 引用都必须先 import 再用短名（含 Instant）。
import java.time.Duration
import java.time.Instant
import java.time.ZoneId
import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter

plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)

    alias(libs.plugins.ksp)
}

/**
 * 按构建日期生成版本号，避免硬编码：
 * - versionCode = yyyyMMddHH（10 位，单调递增，一天内多次构建也能区分）
 * - versionName = yyyy.MM.dd（人类可读）
 *
 * ★ 用日期而非语义化版本的原因：语义化版本需要人工维护且可能回退
 *   （如 1.3.1 → 1.0.0），而回退会让已装旧版的用户收不到更新提示
 *   —— UpdateChecker 比较的是 versionName。日期天然单调递增，从根上避免此问题。
 *
 * 时区固定 UTC+8（Asia/Shanghai），保证本地与 CI 构建结果一致。
 */
/**
 * 构建时间来源（按优先级）：
 * 1. `-PbuildTime=<epochMillis>` —— CI 传入。**必须这么做**：一次发版里
 *    `printVersion` 与 `assembleRelease` 是两次独立 Gradle 调用，各自调
 *    `ZonedDateTime.now()` 会在跨整点时算出不同 versionCode，
 *    导致 tag 与 APK 内嵌版本不一致。CI 固定传同一个时间戳即可保证同源。
 * 2. 环境变量 `YUNX_BUILD_TIME`
 * 3. 兜底 `now()`（本地构建）
 */
val buildTime: ZonedDateTime = run {
    val raw = (project.findProperty("buildTime") as String?) ?: System.getenv("YUNX_BUILD_TIME")
    val epoch = raw?.toLongOrNull()
    epoch?.let { Instant.ofEpochMilli(it).atZone(ZoneId.of("Asia/Shanghai")) }
        ?: ZonedDateTime.now(ZoneId.of("Asia/Shanghai"))
}
/**
 * versionCode = **1970-01-01 起的分钟数**（epoch minutes）。
 *
 * ★ 为什么不是 `yyyyMMddHHmm`（12 位）：versionCode 是 Int，上限 2147483647，
 *   该格式必然溢出。而 `yyyyMMddHH`（10 位）精度只到小时 —— 同一小时内
 *   重复构建会算出相同 versionCode，导致 tag 复用、APK 被覆盖但版本号不变，
 *   已安装用户永远收不到更新（静默失效，且无任何提示）。
 *
 * epoch 分钟数目前约 2981 万（8 位），既单调递增、精度到分钟，又远小于上限，
 * 可安全用到 6053 年初（Int 上限对应 6053-01-23）。
 */
val versionCodeInt: Int = Duration.between(
    Instant.EPOCH,
    buildTime.toInstant()
).toMinutes().toInt()
val versionNameStr: String = buildTime.format(DateTimeFormatter.ofPattern("yyyy.MM.dd.HH.mm"))

android {
    namespace = "com.yunx.app"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.yunx.app"
        minSdk = 23
        targetSdk = 34
        versionCode = versionCodeInt
        versionName = versionNameStr

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        getByName("debug") {
            storeFile = file("../debug.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
        }
    }

    buildTypes {
        debug {
            signingConfig = signingConfigs.getByName("debug")
        }
        release {
            isMinifyEnabled = true
        }
    }

    buildFeatures {
        compose = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.fromTarget("17"))
        }
    }
}

dependencies {
    implementation("androidx.compose.material:material-icons-extended")
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation(libs.material)   // 原 libs.material.color.utilities -> 改为官方 Material 主库（含 color.utilities 包）

    implementation(libs.room.runtime)
    implementation(libs.room.ktx)          // 提供协程扩展，如 Flow、suspend
    ksp(libs.room.compiler)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)
    testImplementation("junit:junit:4.13.2")
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}

/**
 * 供 CI 读取版本号：输出 `name=<versionName>` 与 `code=<versionCode>`。
 *
 * ★ versionName 现在由构建日期生成、不再是字面量，CI 不能再靠
 *   `grep versionName | sed` 从源码里抠字符串（抠不到引号内容）。
 *   必须由 Gradle 自己算出来再输出，保证单一数据源。
 */
tasks.register("printVersion") {
    doLast {
        println("name=$versionNameStr")
        println("code=$versionCodeInt")
    }
}
